version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hh_parser
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  web:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      # - "[::]:8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ru_cidrs.map:/etc/nginx/ru_cidrs.map:ro
    depends_on:
      - web
    networks:
      - app_net

networks:
  app_net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.16.238.0/24
        - subnet: fd00:cafe:face::/64

volumes:
  pgdata: