events {}

http {
    resolver 127.0.0.11 valid=30s;

    geo $is_russia {
        default 0;
        # Тестовый IP
        213.0.0.0/8 1;
    }

    server {
        listen 80;
        listen [::]:80;
        charset utf-8;

        # Читаем реальный IP (для тестов с curl)
        set_real_ip_from 0.0.0.0/0; 
        real_ip_header X-Forwarded-For;
        real_ip_recursive on;

        location = /access-denied {
            default_type text/html;
            return 200 "<html><head><meta charset='utf-8'><title>Block</title></head><body><center><h1>ВАМ СЮДА НЕЛЬЗЯ</h1><p>Доступ из вашего региона запрещен.</p></center></body></html>";
        }

        location / {
            if ($is_russia) {
                return 302 /access-denied;
            }

            set $upstream web;
            proxy_pass http://$upstream:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}


